site:
  title: "Antora Docs"
  url: https://marzelwidmer.github.io.
  start_page: component-a::index
  robots: allow

git:
  ensure_git_suffix: false

content:
  branches: master
  sources:
  - url: https://github.com/marzelwidmer/antora-component-a.git
#  - url: ./../antora-component-a
ui:
  bundle:
    url: "https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable"
    snapshot: true
  output_dir: ui-bundle
  supplemental_files: ./supplemental-ui

output:
  dir: ./public

asciidoc:
  attributes:
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
